Improved queue
scylla-zpp-blas/linear-algebra pull request #12
Opened 2021-04-20 15:29 UTC by Lorak-mmk

- Added produce version that lets you insert multiple tasks (hopefully more efficiently than doing it one by one)
- You can now return results from task: `void mark_as_finished(int64_t id, const response& response);`
- consume now returns std::optional, instead of throwing exception on empty queue.

2021-04-20 21:37 UTC, jbhayven approved these changes
Looks ok.

2021-04-20 21:37 UTC, jbhayven commented on include/scylla_blas/queue/scylla_queue.hh
> +    std::vector<int64_t> produce(const std::vector<task> &tasks);
If possible, I'd go even as far as to support various types of containers (i.e. maps, sets etc.), but I have no idea how to do that without writing tonnes of code, so I'd say it's perfectly fine as it is now.

2021-04-20 21:37 UTC, jbhayven commented on src/main.cc
> +        if(!opt) {
`if (!opt)`

2021-04-21 21:55 UTC, Lorak-mmk commented on include/scylla_blas/queue/scylla_queue.hh
> +    std::vector<int64_t> produce(const std::vector<task> &tasks);
That would require significant changes in code, so I'd like to avoid it now.

2021-04-21 22:37 UTC, Rhantolq commented on src/scylla_blas/queue/scylla_queue.cc
> +        return produce_vec_simple(tasks);
Does this produce vectors? If it does not, maybe produce_many_* ?

2021-04-22 18:17 UTC, Rhantolq requested changes

2021-04-22 18:18 UTC, Rhantolq commented on tests/queue.cc
> +    for(auto val : values) {
`for (...`

2021-04-23 14:19 UTC, Rhantolq approved these changes

2021-04-23 14:19 UTC, Rhantolq commented on tests/queue.cc
> +    for(auto val : values) {
for (

2021-04-23 14:19 UTC, Rhantolq commented on tests/queue.cc
> +        for(auto val : values) {
for (

2021-04-23 19:24 UTC, merged