Jbhayven/blas semifinal
scylla-zpp-blas/linear-algebra pull request #15
Opened 2021-05-09 14:19 UTC by jbhayven

Implemented essentially all key routines (several less important, such as duplicates of already existing operations for symmetrical structures, and those not logically compatible, such as operations on packed representations, were left out).

Tested have been all operations included in tests (this means I haven't tested level 3's `syr(2)k` operations yet).

Comment: we need to take a thorough look at our insertion/update operations in matrices and vectors, as their behaviour seems erratic at times. I suppose we can distinguish between `insertion` (inserting new values into empty spaces? or replacing old values if there are collisions?) and `update` (replace a whole substructure: segment, row, block), yet insertions seem to at time replace old values, and at times not. While at it, it would be great if we allowed for effective value deletion (e.g. I know it may be hard to delete an entire block with a single 'DELETE' query, but maybe we could get_block and then perform a bulk_delete on the list of obtained indices?)

2021-05-12 14:01 UTC, Lorak-mmk requested changes
Really great work overall, wow.
I didn't review tests, I think it makes more sense to do that after Robert finishes refactoring them.
- Not specific to this PR, but I don't like that std::cerr is used as logging mechanism - we should make logging functions or macros, wrapping fmt::print, allowing us to do thigs like formatting, importance levels etc

2021-05-12 17:48 UTC, Lorak-mmk commented
Also, I don't like the idea of the additional test_init binary, I think it should instead be done with Boost's global fixture: https://www.boost.org/doc/libs/1_61_0/libs/test/doc/html/boost_test/tests_organization/fixtures/global.html

2021-05-13 17:38 UTC, Lorak-mmk commented on include/scylla_blas/vector.hh
> +        _session->execute("BEGIN BATCH " + updates + "APPLY BATCH;");
There is similiar situation in matrix.hh. Could you please not change that? I will change that in my PR

2021-05-14 08:56 UTC, Lorak-mmk commented on include/scylla_blas/vector.hh
> +        _session->execute("BEGIN BATCH " + updates + "APPLY BATCH;");
There are similiar problems in matrix

2021-05-14 14:20 UTC, jbhayven commented on src/scylla_blas/blas_level_1.cc
> +                           X.id, X.length, Y.id, Y.length));
I guess it's typecast to an exception somehow? Though, I agree, it's better to make it explicit.

2021-05-14 14:30 UTC, jbhayven commented on include/scylla_blas/vector.hh
> +        _session->execute("BEGIN BATCH " + updates + "APPLY BATCH;");
1. 2. Is there a way to include prepared statements in batch queries?
3. I think the intended behaviour is to 'insert' zeroes by removing values at corresponding indices, so as not to store any values equal to 0 (or below `eps`, for that matter). I don't know which of the update/insert pair is more appropriate in this context. 

4. I don't remember, but we can restrict the method's semantics to pure insertion and skip the deleting part.

2021-05-14 14:31 UTC, jbhayven commented on src/scylla_blas/vector.cc
> +                "SELECT * FROM blas.vector_{} WHERE segment = ? AND idx = ? ALLOW FILTERING;", id),
@s-stol

2021-05-14 14:31 UTC, jbhayven commented on src/scylla_blas/vector.cc
> +                "SELECT * FROM blas.vector_{} WHERE segment = ? ALLOW FILTERING;", id),
@s-stol

2021-05-14 14:34 UTC, jbhayven commented on include/scylla_blas/vector.hh
> +    }
@s-stol

2021-05-14 14:35 UTC, jbhayven commented on include/scylla_blas/vector.hh
> +    }
I agree with this comment, though it's not my code, so I can't tell if there were any special reasons for doing it this way.

2021-05-14 16:04 UTC, Lorak-mmk commented on src/scylla_blas/blas_level_1.cc
> +                           X.id, X.length, Y.id, Y.length));
In C++ you can throw anything.
You can do
`throw 3`
and later `catch (int e)`
So you are throwing a string here.

2021-05-14 16:15 UTC, Lorak-mmk commented on include/scylla_blas/vector.hh
> +        _session->execute("BEGIN BATCH " + updates + "APPLY BATCH;");
1. I think it should just work? If you have `scmd::batch_query batch(CASS_BATCH_TYPE_UNLOGGED);`, and a `scmd::prepared_query query`, then you should be able to do `auto stmt = query.get_statement(); batch.add_statement(stmt.bind(args))`. After current PR to driver is merged, you could also merge those 2 lines: `batch.add_statement(query.get_statement().bind(args))`
2. Ah, I'm blind, I didn't see that either delete or insert is executed, not both :D
3. Sorry, I thought that each inserted value is deleted first, so my original comment is not important.

2021-05-20 16:56 UTC, jul-stas commented on src/scylla_blas/vector.cc
> +                "SELECT * FROM blas.vector_{} WHERE segment = ? AND idx = ? ALLOW FILTERING;", id),
A general remark: `select *` in prepared statements is prone to schema changes and it's better to avoid it.

2021-05-21 22:11 UTC, s-stol commented on src/scylla_blas/vector.cc
> +                "SELECT * FROM blas.vector_{} WHERE segment = ? ALLOW FILTERING;", id),
This is indeed not necessary here, fixed

2021-05-21 22:14 UTC, s-stol commented on include/scylla_blas/vector.hh
> +    }
Yes, this method didn't make much sense, fixed

2021-05-21 22:16 UTC, s-stol commented on include/scylla_blas/vector.hh
> +        _session->execute("BEGIN BATCH " + updates + "APPLY BATCH;");
I updated the method (for vectors) so that it uses batch queries supported by driver.

2021-05-27 17:37 UTC, Rhantolq approved these changes
If you have time, add scylla_blas::id_t for typing id's

2021-05-27 17:37 UTC, Rhantolq commented on include/scylla_blas/matrix.hh
>      const index_type id;
remove public since we have getters

2021-05-27 17:37 UTC, Rhantolq commented on include/scylla_blas/routines.hh
> +    vector<float>& sgemv(const enum TRANSPOSE TransA,
& in wrong place across the file

2021-05-27 17:37 UTC, Rhantolq commented on include/scylla_blas/vector.hh
> +    }
updates or inserts here should either have a comment documenting whether they overwrite currently existing values or should have a method name that specifies it clearly (insert_or_replace for example)

2021-05-27 17:37 UTC, Rhantolq commented on include/scylla_blas/vector.hh
> +    }
similarly for matrix

2021-05-27 17:39 UTC, Rhantolq commented
meging asap without much refactoring would be welcome

2021-05-30 18:42 UTC, merged