Added linear solver
scylla-zpp-blas/linear-algebra pull request #26
Opened 2021-05-31 16:05 UTC by s-stol

2021-05-31 19:42 UTC, Lorak-mmk requested changes

2021-05-31 19:42 UTC, Lorak-mmk commented on examples/linear_solver/CMakeLists.txt
> +find_package(Boost 1.60.0 COMPONENTS system thread filesystem unit_test_framework program_options REQUIRED )
Does the solver use any of those modules? Does it use boost at all?

2021-05-31 19:42 UTC, Lorak-mmk commented on examples/linear_solver/CMakeLists.txt
> +target_link_libraries(example PUBLIC scylla_blas "${Boost_LIBRARIES}")
Again, does the solver use boost at all?

2021-05-31 19:42 UTC, Lorak-mmk commented on examples/linear_solver/CMakeLists.txt
> +add_executable(example example.cc jacobi_solver.cc jacobi_solver.hh)
I don't like the executable name. Something like `solver` or `jacobi_solver` or `linear_solver` would be better

2021-05-31 19:42 UTC, Lorak-mmk commented on examples/linear_solver/example.cc
> +#include <scylla_blas/matrix.hh>
Be consistent with `<>` and `""` - use `<>` for scylla_blas, and put those above `"jacobi_solver.hh"` (standatd libs, then external libs, then project libs, the program headers)

2021-05-31 19:42 UTC, Lorak-mmk commented on examples/linear_solver/example.cc
> +    std::string scylla_port = argv[2];
It would be nice to use default port (it is in config.hh) when user doesn't specify one

2021-05-31 19:42 UTC, Lorak-mmk commented on examples/linear_solver/example.cc
> +    scylla_blas::index_type N = 100;
I don't like the magic number here. What this number means, why is it 100? Could it be a cmd line parameter or a config value?

2021-06-01 10:07 UTC, Rhantolq commented on examples/linear_solver/example.cc
> +    }
it is generally better to use `insert_values` or `insert_row` when constructing a matrix.
You don't need to change it though, as we should create "load_from_file" option in our project anyway.

2021-06-01 10:25 UTC, Rhantolq commented on examples/linear_solver/jacobi_solver.hh
> +#define NUM_OF_ITERATIONS 1000
Don't use #define

2021-06-01 10:53 UTC, Rhantolq requested changes

2021-06-01 10:53 UTC, Rhantolq commented on examples/linear_solver/jacobi_solver.hh
> +
Add tabbing after private

2021-06-01 10:53 UTC, Rhantolq commented on examples/linear_solver/jacobi_solver.hh
> +#define NUM_OF_ITERATIONS 1000
Don't use #define

2021-06-01 10:53 UTC, Rhantolq commented on examples/linear_solver/jacobi_solver.hh
> +
remove newline

2021-06-01 10:53 UTC, Rhantolq commented on examples/linear_solver/jacobi_solver.hh
> +// TODO fix CMakeLists
remove todo (probably rebase on master first)

2021-06-01 10:53 UTC, Rhantolq commented on examples/linear_solver/jacobi_solver.cc
> +
remove newline

2021-06-03 11:19 UTC, Lorak-mmk commented on examples/linear_solver/example.cc
> +    for (scylla_blas::index_type i = 1; i <= N; i++) {
This way of inserting will be painfully slow. Please create vector of values and use `insert_block`/`insert_row`/`insert_values`

2021-06-03 16:15 UTC, Lorak-mmk approved these changes

2021-06-04 18:24 UTC, Rhantolq approved these changes

2021-06-14 18:06 UTC, closed without merging

2021-06-14 18:06 UTC, Lorak-mmk commented
Already merged with other PRs