Refactor, benchmark, performance improvements
scylla-zpp-blas/linear-algebra pull request #27
Opened 2021-06-03 10:57 UTC by Lorak-mmk

Done:
- Adding identifier type (`scylla_blas::id_t`), as requested by @jbhayven 
- Renamed index_type to index_t
- BLOCK_SIZE is now not global, but saved per matrix
- Refactored matrix and vector classes (field/method order, driver usage, added nonstatic resize, etc.)
- Fixed bug in tests (they were using abs instead of std::abs, abs works on integers)
- Worker concurrency is now not global, but saved per scheduler. Same with scheduler sleep time.
- Worker sleep time and max retries are now settable with command line arguments.
- Sleeps now have microsecond accuracy.

TODO:
- Implement simple benchmark program
- Performance optimizations

2021-06-06 17:45 UTC, jbhayven reviewed
Impressive work. 
The comments are mostly cosmetic.
I agree with the need for block/segment size compatibility validation but I also agree that it's not among our current priorities.

2021-06-06 17:45 UTC, jbhayven commented on benchmark/insert_benchmark.cc
> +            }
Here, too. Please remove this.

2021-06-06 17:45 UTC, jbhayven commented on benchmark/insert_benchmark.cc
> +            }
And here

2021-06-06 17:45 UTC, jbhayven commented on benchmark/insert_benchmark.cc
> +            }
Here as well.

2021-06-06 17:45 UTC, jbhayven commented on benchmark/insert_benchmark.cc
> +            pkey++;
And here.

2021-06-06 17:45 UTC, jbhayven commented on benchmark/main.cc
> +        std::cout << bs << " " << ps << " " << r.setup_time << " " << r.proc_time << " " << r.teardown_time << "\n";
Why mix log and std::cout?

2021-06-06 17:45 UTC, jbhayven commented on examples/arnoldi/arnoldi.hh
>          }
It looks like we should allow to pass a desired block size in the matrix constructor, though I guess it's not a priority for now.

2021-06-06 17:45 UTC, jbhayven commented on include/scylla_blas/matrix.hh
> +     * E.g. in a matrix that is 2 blocks wide the rightmost column belongs to the block number 2.
the rightmost block is located in the column number 2

2021-06-06 17:45 UTC, jbhayven commented on include/scylla_blas/vector.hh
>      // Should we make these private, with accessors?
Is this comment relevant anymore?

2021-06-06 17:45 UTC, jbhayven commented on include/scylla_blas/vector.hh
> +    index_t block_size;
This should be called `segment_size` unless we really want a uniform naming system.

2021-06-06 17:45 UTC, jbhayven commented on src/main.cc
> +                    "How many time worker should attempt to do a task");
Aren't "sleep" and "retries" self-explanatory enough?

Well, maybe not. It's just a thought I had.

2021-06-06 17:45 UTC, jbhayven commented on src/scylla_blas/blas_level_3.cc
> +    LogDebug("Preparing multiplication task...");
I don't think this log should be here at all. It's probably some old, leftover code. 
Either remove it (as well as its counterparts from other blas_level files) or change to something more accurate.
Maybe "Creating block-based subtasks..."?

2021-06-06 17:45 UTC, jbhayven commented on src/scylla_blas/queue/worker_proc.cc
> +        LogDebug("New secondary task obtained; id = {}", opt.value().first);
Maybe change it to "secondary task (subtask)" so that the message is clearer.
Either that or remove all references to "secondary tasks", as having two names for the same thing can be confusing to the user.

2021-06-06 17:45 UTC, jbhayven commented on src/scylla_blas/vector.cc
> +void scylla_blas::basic_vector::update_meta() {
Rename as "update_from_meta" or "sync_with_meta" or "get_meta_from_database".
"update_meta" implies that this somehow updates the metadata kept in Scylla.

2021-06-06 19:31 UTC, Lorak-mmk commented on benchmark/main.cc
> +        std::cout << bs << " " << ps << " " << r.setup_time << " " << r.proc_time << " " << r.teardown_time << "\n";
I did it that way so it is easy to copy raw benchmark results.

2021-06-06 19:33 UTC, Lorak-mmk commented on examples/arnoldi/arnoldi.hh
>          }
Much better place would be the init method - and in fact I already added it there, just didn't think about it while writing this code. I'll fix that.

2021-06-06 19:50 UTC, Lorak-mmk commented on src/main.cc
> +                    "How many time worker should attempt to do a task");
When reading help for programs I really don't like cmdline options without any, even laconic, description.

2021-06-06 19:58 UTC, Lorak-mmk commented on include/scylla_blas/vector.hh
> +    index_t block_size;
I see just one issue - when launching programs (benchmark, arnoldi), the command line mentions block size. Adding segment size flag will be strange (as we want the two to be the same), but not adding it will cause block_size flag setting segment_size - which is also not perfect. Can we leave it as it is, for now?

2021-06-06 20:03 UTC, Lorak-mmk commented on src/scylla_blas/queue/worker_proc.cc
> +        LogDebug("New secondary task obtained; id = {}", opt.value().first);
This seems to be the only occurence of the word "secondary". I changed it to subtask.

2021-06-06 20:06 UTC, Lorak-mmk commented on include/scylla_blas/matrix.hh
> +     * E.g. in a matrix that is 2 blocks wide the rightmost column belongs to the block number 2.
I don't understand?

2021-06-07 09:09 UTC, jbhayven commented on src/main.cc
> +                    "How many time worker should attempt to do a task");
I meant "sleep" rather than "worker_sleep" an "retries" rather than "worker_retries"; descriptions are good.

2021-06-07 09:11 UTC, jbhayven commented on include/scylla_blas/vector.hh
> +    index_t block_size;
I'd prefer `block_size` flag to set both block and segment size, but, well, eh. We can... I guess?

2021-06-07 09:12 UTC, jbhayven commented on include/scylla_blas/matrix.hh
> +     * E.g. in a matrix that is 2 blocks wide the rightmost column belongs to the block number 2.
The comment should say `E.g. in a matrix that is 2 blocks wide the rightmost block is located in the column number 2.` rather than `E.g. in a matrix that is 2 blocks wide the rightmost column belongs to the block number 2.` 
Blocks are in columns, not the other way around.

2021-06-14 12:17 UTC, Rhantolq requested changes
Solid work, GJ.
Benchmark code can be made much more clean and easy to read. I think it is not a good practice to shorten variable names (especially when using IDE).

2021-06-14 13:22 UTC, Lorak-mmk commented on benchmark/benchmark.cc
> +    size_t ret = w * h / 5; // 20% load
Already done in bnechmarking changes

2021-06-14 13:49 UTC, Lorak-mmk commented on benchmark/benchmark.cc
> +    auto t1 = std::chrono::high_resolution_clock::now();
This function has 4 lines, it is perfectly readable.

2021-06-14 13:50 UTC, Lorak-mmk commented on benchmark/insert_benchmark.cc
> +    auto t1 = std::chrono::high_resolution_clock::now();
This function has 5 lines, it is perfectly readable.

2021-06-14 14:44 UTC, Rhantolq approved these changes
My previous comments that we agreed on will be fixed in next PR.

2021-06-14 18:03 UTC, jbhayven approved these changes

2021-06-14 18:05 UTC, merged