Benchmarking changes
scylla-zpp-blas/linear-algebra pull request #29
Opened 2021-06-10 18:12 UTC by Lorak-mmk

2021-06-13 10:51 UTC, jbhayven requested changes
Not much to change, mostly cosmetic stuff. I can implement the vector generation, if we decide it is necessary.

2021-06-13 10:51 UTC, jbhayven commented on benchmark/benchmark.cc
> +    //wm->clear_all();
uncomment

2021-06-13 10:51 UTC, jbhayven commented on benchmark/benchmark.cc
> +    //scylla_blas::matrix<float>::drop(session, w_matrix_id);
uncomment

2021-06-13 10:51 UTC, jbhayven commented on benchmark/benchmark.cc
> +    scheduler.srmgen(matrix_load, *lm);
We should add corresponding methods for vectors and have the load parameter as a 'double' in all cases.

2021-06-13 10:51 UTC, jbhayven commented on benchmark/benchmark.cc
> +    //wv->clear_all();
uncomment

2021-06-13 10:51 UTC, jbhayven commented on benchmark/benchmark.cc
> +    //scylla_blas::vector<float>::drop(session, w_vector_id);
uncomment

2021-06-13 10:51 UTC, jbhayven commented on benchmark/benchmark.cc
> +    //rv->clear_all();
uncomment

2021-06-13 10:51 UTC, jbhayven commented on benchmark/benchmark.cc
> +    //scylla_blas::vector<float>::drop(session, r_vector_id);
uncomment

2021-06-13 10:51 UTC, jbhayven commented on benchmark/main.cc
> +    std::cout << "End time: " << std::ctime(&end_time_t);
Double check to make sure if we want it as out and not logs.

2021-06-13 10:51 UTC, jbhayven commented on examples/arnoldi/main.cc
>      //    matrix_ptr = std::make_shared<scylla_blas::matrix<T>>(session, id);
what's this?

2021-06-13 10:51 UTC, jbhayven commented on include/scylla_blas/matrix.hh
> +                        (prev_block != -1 && get_block_col(val.col_index) != prev_block)) {
shouldn't this be checked for both block row and block column?
Btw, if we have to do this, I'd rather split the vector of values into a vector of blocks and perform a bunch of block-based async queries (possibly further subdivided).

2021-06-13 10:51 UTC, jbhayven commented on include/scylla_blas/routines.hh
> +            if (response.value().type == proto::R_NONE) continue;
I know it's an old method, but perhaps we should try catching a no value exception?

2021-06-13 10:51 UTC, jbhayven commented on include/scylla_blas/routines.hh
> +    }
suggestion: if `q` is the number of queues used (now equal to _current_worker_count), and `n` is the number of subtasks, then maybe we should try limiting the value of `q` so that `q^2 <= n`? Or maybe `100q <= n`? It could reduce the time of scheduling with the main task queue.

Though, if two workers are enough to impose a significant overhead, then maybe it's not worth it.

2021-06-13 10:51 UTC, jbhayven commented on include/scylla_blas/routines.hh
> +                    .type = scylla_blas::proto::NONE,
Perhaaaaaps it would be nice to have a separate ID for subtasks?

Nah, whatever. Just saying. It's irrelevant, so maybe it's better to leave it as is. Changing it is pointless, could be risky and the workers don't care anyway.

2021-06-13 10:51 UTC, jbhayven commented on include/scylla_blas/routines.hh
> +        }
Note: consider NOT truncating; having more queues than needed is mostly harmless and can reduce the time spent de-initializing and re-initializing queues.

2021-06-13 10:51 UTC, jbhayven commented on include/scylla_blas/routines.hh
> +            _scheduler_sleep_time(DEFAULT_SCHEDULER_SLEEP_TIME_MICROSECONDS)
fix tabulation?

2021-06-13 10:51 UTC, jbhayven commented on include/scylla_blas/routines.hh
> +    matrix<double> &drmgen(double alpha, matrix<double> &A);
As mentioned earlier, we should add versions of these meant for vectors.

2021-06-13 10:51 UTC, jbhayven commented on include/scylla_blas/utils/scylla_types.hh
> +//#include <boost/core/demangle.hpp>
delete

2021-06-13 10:51 UTC, jbhayven commented on src/scylla_blas/blas_level_2.cc
> +            }
Now that I think about it, maybe what we need is not a struct (or a union of structs), but a serialized argument tuple (like std::args or sth)? Obviously, now it's to late for that, but I really hate this method of struct initialization that we are using right now. It's way too low-level to my taste.

And yes, I know it's my design. I'm just saying that it could be improved. Maybe add a /* TODO */ to signalize that we are aware of this.

2021-06-13 10:51 UTC, jbhayven commented on src/scylla_blas/blas_level_2.cc
>                                              });
Fix formatting

2021-06-13 10:51 UTC, jbhayven commented on src/scylla_blas/blas_level_2.cc
> +    return A;
Move to a separate file with an appropriate name (and add the vector versions there?). Or to the scheduler declaration (not a fan of this idea).

2021-06-13 10:51 UTC, jbhayven commented on src/scylla_blas/matrix.cc
> +        stmt.set_timeout(0);
I needed the timeout setting for the tests on my machine, but it may ultimately be unnecessary.

2021-06-13 10:51 UTC, jbhayven commented on src/scylla_blas/queue/scylla_queue.cc
> +    if (session_ptr == nullptr) return;
Is this safe? Doesn't it indicate an error?

2021-06-13 10:51 UTC, jbhayven commented on src/scylla_blas/queue/worker_proc.cc
> +        } while(segment_idx != subtask.index );
Add a comment explaining that this fetching method is used to optimize accesses to the structure.

2021-06-13 10:51 UTC, jbhayven commented on src/scylla_blas/queue/worker_proc.cc
> +        A.insert_block(row, column, block);
Improve formating by adding empty lines.

2021-06-13 10:51 UTC, jbhayven commented on tests/blas_level_1/vector_copy.cc
> +    print_vector(*vector2);
cout or log?

2021-06-13 10:51 UTC, jbhayven commented on tests/test_utils.hh
> +void print_matrix_octave(const scylla_blas::matrix<T> &matrix) {
I don't think it is a good idea to have a method print straight to stdout. This has a very limited usage (e.g. we can't put this in logs). A function returning a string (or a stream) would be better.

2021-06-13 10:51 UTC, jbhayven commented on tests/vector_utils.hh
> +        throw std::runtime_error(fmt::format("Not enough values in vector ({}/{}). Fill with zeroes.", values.size(), whole.back().index));
I would not (and do not) understand this error.

2021-06-13 11:10 UTC, Lorak-mmk commented on benchmark/benchmark.cc
> +    //wm->clear_all();
It would be better to either delete those lines, or add command line flag that will be required to execute them

2021-06-13 11:10 UTC, Lorak-mmk commented on benchmark/benchmark.cc
> +    //scylla_blas::matrix<float>::drop(session, w_matrix_id);
It would be better to either delete those lines, or add command line flag that will be required to execute them

2021-06-13 11:13 UTC, Lorak-mmk commented on benchmark/main.cc
> +    std::cout << "End time: " << std::ctime(&end_time_t);
Yes, it is that way to allow easy copying of benchmark results.

2021-06-13 11:14 UTC, Lorak-mmk commented on tests/vector_utils.hh
> +        throw std::runtime_error(fmt::format("Not enough values in vector ({}/{}). Fill with zeroes.", values.size(), whole.back().index));
I also don't understand it - I didn't write it, just edited. Feel free to change it

2021-06-13 11:15 UTC, Lorak-mmk commented on tests/test_utils.hh
> +void print_matrix_octave(const scylla_blas::matrix<T> &matrix) {
Function returning string sounds good. Printing to stdout may be desired when you want to copy results.

2021-06-13 11:16 UTC, Lorak-mmk commented on tests/blas_level_1/vector_copy.cc
> +    print_vector(*vector2);
Those lines should probably deleted - I added them to debug tests

2021-06-13 11:16 UTC, Lorak-mmk commented on tests/blas_level_1/vector_copy.cc
> +    print_vector(*vector2);
If not deleted, LogDebug sounds good

2021-06-13 11:19 UTC, Lorak-mmk commented on src/scylla_blas/queue/scylla_queue.cc
> +    if (session_ptr == nullptr) return;
session_ptr can be null in a moved-from queue

2021-06-13 11:21 UTC, Lorak-mmk commented on src/scylla_blas/matrix.cc
> +        stmt.set_timeout(0);
I think it would be nice to get ride of those set_timeoutts, at least in queries that don't modify schemas (CREATE TABLE, DROP KEYSPACE, TRUCNATE, etc)

2021-06-13 11:23 UTC, Lorak-mmk commented on src/scylla_blas/blas_level_2.cc
> +            }
The proper solution would be to use protobuf / flatbuf

2021-06-13 11:23 UTC, Lorak-mmk commented on src/scylla_blas/blas_level_2.cc
> +            }
But yeah, it's not the change we want to introduce right now

2021-06-13 11:27 UTC, Lorak-mmk commented on include/scylla_blas/routines.hh
> +        }
It may not be so harmless. The queue_data table is partitioned by queue_id, so if one queue has a lot of tasks, we get a big partition - for that reason it would probably make sense to also call .reset() on main queue after blas routine. Also, .reset() uses one unprepared statement, it should be changed to prepared

2021-06-13 11:30 UTC, Lorak-mmk commented on include/scylla_blas/routines.hh
> +            if (response.value().type == proto::R_NONE) continue;
You mean the situation, when worker should insert a response but didn't? Is it even possible, assuming no bugs in worker code?

2021-06-13 11:31 UTC, Lorak-mmk commented on include/scylla_blas/routines.hh
> +    }
That would make sense - but it would require further benchmarking to know what is the best limit.

2021-06-13 11:35 UTC, Lorak-mmk commented on include/scylla_blas/matrix.hh
> +                        (prev_block != -1 && get_block_col(val.col_index) != prev_block)) {
I think that this method should be private. Users should use insert_row, insert_block, update_row. That way, current code of insert_values would be corrent (as it is corrent assuming all passed values are in one block or in one row). Also, cen we get rid of insert_value? Probably not, but it really shouldn't be used.

2021-06-13 11:36 UTC, Lorak-mmk commented on examples/arnoldi/main.cc
>      //    matrix_ptr = std::make_shared<scylla_blas::matrix<T>>(session, id);
I don't understand? If you mean commented-out line, it should be deleted - matrix_ptr is now and argument

2021-06-13 11:41 UTC, jbhayven commented on tests/test_utils.hh
> +void print_matrix_octave(const scylla_blas::matrix<T> &matrix) {
> Printing to stdout may be desired when you want to copy results.
Even then, it is IMO better to get a representation (string or a vector of strings for each line), and only then print it.

2021-06-13 13:09 UTC, jbhayven commented on include/scylla_blas/matrix.hh
> +                        (prev_block != -1 && get_block_col(val.col_index) != prev_block)) {
Perhaps it should be private. I will try to make it so.

As for the latter part of the comment, I think insert_value is appropriate for single operations (such as the givens rotations, which we haven't implemented). We could get rid of it, but I think it is reasonable to assume that a user will be aware that this can be used only in very specific situations.

2021-06-13 13:10 UTC, jbhayven commented on include/scylla_blas/routines.hh
> +            if (response.value().type == proto::R_NONE) continue;
Indeed, I do not think this is possible.

2021-06-13 13:10 UTC, jbhayven commented on include/scylla_blas/routines.hh
> +    }
Then I will simply leave a comment.

2021-06-13 13:24 UTC, jbhayven commented on tests/test_utils.hh
> +void print_matrix_octave(const scylla_blas::matrix<T> &matrix) {
Move to the matrix class, the stream is now passed as a parameter.

2021-06-13 13:31 UTC, jbhayven commented on tests/vector_utils.hh
> +        throw std::runtime_error(fmt::format("Not enough values in vector ({}/{}). Fill with zeroes.", values.size(), whole.back().index));
The entire function containing this exception is ugly. It is usable only in a very specific context, and behaves strangely.

If the scylla vector is too short, an exception is thrown.
If it is too long, it is only checked if the trailing part is composed  only of zeroes.
If the vectors are of equal length, the first difference is returned as an std::optional. (If they are equal, a nullopt is returned.

(I have also noted that an explicit constructor of std::optional is used in one place, instead of std::make_optional).

2021-06-13 14:27 UTC, jbhayven commented on examples/linear_solver/example.cc
> -    m.insert_values(matrix_values);
This is... actually not diagonally dominant?

2021-06-13 14:29 UTC, jbhayven commented on examples/linear_solver/example.cc
> -    m.insert_values(matrix_values);
(N is globally set to 10)

2021-06-13 18:23 UTC, jbhayven commented on tests/vector_utils.hh
> +        throw std::runtime_error(fmt::format("Not enough values in vector ({}/{}). Fill with zeroes.", values.size(), whole.back().index));
I mean, I can guess the context of this one, but if the function has to be so specific, it should probably be in anonymous namespace somewhere else

2021-06-13 18:28 UTC, Lorak-mmk commented on CMakeLists.txt
> +        src/scylla_blas/blaslike.cc)
Move ')' to next line

2021-06-13 18:28 UTC, Lorak-mmk commented on benchmark/benchmark.cc
> +                LogDebug("\tAutoclean off: skipping teardown");
Set r.teardown_time to 0 here

2021-06-13 18:28 UTC, Lorak-mmk commented on benchmark/benchmark.cc
> +        LogDebug("\tAutoclean off: skipping destroy");
Set result.destroy_time to 0 here.

2021-06-13 18:28 UTC, Lorak-mmk commented on benchmark/main.cc
> +            ("autoclean", "Delete all structures after the benchmark")
`("autoclean", po::bool_switch(&options.autoclean), "Delete all structures after the benchmark")`

2021-06-13 18:28 UTC, Lorak-mmk commented on benchmark/main.cc
> +        if (vm.count("autoclean")) options.autoclean = true;
delete this line

2021-06-13 19:23 UTC, jbhayven approved these changes

2021-06-14 14:48 UTC, Lorak-mmk commented on include/scylla_blas/routines.hh
> +        LogInfo("Scheduled tasks {}-{} to queue {}", task_id, task_id + tasks.size() - 1, _main_worker_queue.get_id());
It would only affect logs - wrong value would be printed.

2021-06-14 17:49 UTC, Rhantolq approved these changes

2021-06-14 17:57 UTC, merged