simple matrix multiplication added
scylla-zpp-blas/linear-algebra pull request #5
Opened 2021-01-12 01:36 UTC by jbhayven

Waiting for constructive criticism and suggestions; I don't like the way our template code is entirely stored in the header files, but wouldn't moving it to separate .cc sources require us to specialize the templates in advance (at least by the virtue of declaring their parametrized versions)? 

Not that it is much of an issue (in our case, we are limited by Scylla's data types anyway), rather, it looks boilerplatey and thus suboptimal to me (as it seems this would be needed for every class/function we declare; maybe we could take advantage of a custom macro?). 

Moreover, I am not sure if I'm satisfied with making scylla_blas a namespace (though I do consider it a more typical C++ practice than a class with public static methods; on the other hand, if we intend to blackbox the 'session' and other aspects of database interaction, a class with a handful of public (yet non-static) methods would indeed be the default solution).

Next, there is the 'vector record' class that i am not too fond of (ideally, I would have it inherit after an appropriately parametrized version of `std::pair<>` with "index" and "value" aliasing (or even replacing) the "first" and "second" attributes. Then, maybe it is better to keep full control over the class and not to worry about its limitations (stemming from an itself limited implementation). Opinions?

Lastly, I would very much like to reform the catalogue structure (in my opinion, it seems unacceptable to have non-main sources in the main directory, not to mention keeping *all* sources in the main directory), but I'm not sure what the correct approach would be. Do we want to treat Scylla-based matrices and RAM-based vectors as similar kinds of data structure, or would we want to keep them separate for the sake of clarity? On the other hand, the files are too few to make any meaningful directory tree whose folder to source code file ratio wouldn't approach 1.

For now all methods of the matrix class are synchronic – are we going to make them return seastar promises in the future versions? Obviously, a lot can be done to improve the `scylla_matrix`'s performance still - off the top of my head: we could buffer insertions (should we?) and data loading – now, the question is, what kinds of solutions are already employed by Scylla, and would obfuscating our matrices with their duplicates benefit us in any way? (E.g. if queries are buffered in Scylla – are they? – it might be quicker to access a RAM buffer than a DB-based buffer: but is it?).

As the very last note: you might need to slightly modify the "modern C++ driver" in order to be able to compile the code due to some dependency issues (namely: the driver doesn't come with fmt included; however, our repository does, so there may as well be no problems at all, in particularly, if you have fmt installed locally on your machine).

2021-01-13 17:07 UTC, Lorak-mmk commented
I will try to review this PR later, right now just 1 thing: Fixed version of driver is pushed, so you can switch to it and not modify it locally. Also, I'd recommend switching driver submodule from master branch to  a tag in release branch (which was just created :D), otherwise merging backwards-incompatibile changes into driver's master is going to break this project. You should be able to to that using those commands (in case of any problems conact me):
```
git submodule update --recursive --remote
cd lib/driver
git checkout v0.1
cd ../..
git add lib/driver
git commit -m 'Updated driver to v0.1
```

2021-02-17 20:30 UTC, Rhantolq approved these changes

2021-02-17 20:30 UTC, Rhantolq commented on sparse_matrix_value_generator.hh
> +        void _calc_next_pos() {
do we start with _ for private methods?

2021-02-17 20:30 UTC, Rhantolq commented on scylla_matrix.hh
> +namespace scylla_blas {
remove unnecessary tabs in all namespaces as recommended in https://github.com/scylladb/seastar/blob/master/coding-style.md

2021-02-18 12:09 UTC, Rhantolq approved these changes
rest looks fine

2021-02-18 12:09 UTC, Rhantolq commented on sparse_matrix_value_generator.hh
> +    void _calc_next_pos() {
private method name?

2021-02-21 10:07 UTC, Lorak-mmk requested changes
- "multiply" and "linear-algebra" targets don't compile for me. If they compile on your machine, let me know, I'll provide error log or a fix.
- Regarding folder structure: I agree that having sources in main folder seems bad. I think most common way to structure is to have a "include" folder, with headers used in public interface, and "src" folder with all sources (with more subfolders inside possible ofc). 
- Afaik we won't use seastar, but new version of driver wrapper (PR waiting for review) supports async operations.

2021-02-22 20:11 UTC, jbhayven commented on structure/vector.cc
> +//
+1

2021-02-22 20:17 UTC, jbhayven commented on structure/vector.hh
> +        *this = (*this + other); // Not really optimal, but shouldn't be a huge problem
As far as I recall, the issue is that inheriting from std::vector (instead of, say, std::queue) prohibits us from inserting new elements in the course of iteration. Even if it didn't, each insertion for std::vector would be linear in time – so, as I thought, we'd need to conveniently create a new vector to store the result, anyway.

However, now that I think of it, there exist in-place (more or less) ways to do it, so I'll try to overload the operators the recommended way.

2021-02-22 20:18 UTC, jbhayven commented on matrix_test.cc
> +#include <iostream>
+1

These tests were indeed intended only as temporary mocks for checking if things *work* and for simple debugging.

2021-02-22 20:19 UTC, jbhayven commented on scylla_matrix.hh
> +            CREATE TABLE IF NOT EXISTS blas.{0} (
It's `blas.matrix_{0}` in the latest version (perhaps only in the upcoming PR)

2021-02-22 20:24 UTC, jbhayven commented on scylla_matrix.hh
> +    std::string _id;
I thought it would be nice to have named matrices that we could store in the database regardless of our processes' lifespan (as a sort of non-volatile memory). Technically, we could always initialize them with random ids dependent on time and only present those ids to the users, but I don't consider this too user-friendly.

2021-02-27 09:52 UTC, Rhantolq commented on matrix_value.hh
>  template <class V>
row and column 
or
row_index column_index

2021-02-27 10:43 UTC, Rhantolq approved these changes

2021-02-27 10:43 UTC, Rhantolq commented on structure/item_set.hh
> +#include "../utils/utils.hh"
If you add 
`include_directories(path)`
to CMake, you can just use #include<utils/utils.hh> (which results in #include "path/utils.utils.hh")

2021-02-27 15:06 UTC, Lorak-mmk commented on structure/item_set.hh
> +#include "../utils/utils.hh"
target_include_directories is preferred way to do it.

2021-03-02 16:54 UTC, Rhantolq approved these changes

2021-03-03 22:09 UTC, Lorak-mmk approved these changes
- In the next PR, we need restructuring of directory tree, and moving to Boost test / GTest.

2021-03-03 22:09 UTC, Lorak-mmk commented on scylla_matrix.hh
> +        for (auto &val : block.get_values_raw())
I don't like the update methods, they seem slow? Maybe let's (in the future, not before merge) use async/batch requests etc?

2021-03-05 09:15 UTC, merged