jbhayven/workers and interfaces
scylla-zpp-blas/linear-algebra pull request #9
Opened 2021-03-16 22:10 UTC by jbhayven

Feel free to propose any changes you like. Note that concurrent computations require thorough testing, which hasn't been done yet. 

So you can (and should) also try to run computations (an example included as a test) for two workers simultaneously on your machine and see what happens. In particular, try to adjust the config or test parameters so that the workers will actually try and access queues or matrices simultaneously.

N.B. As of now it is assumed that every matrix is of size `n * n`, where `N = MATRIX_BLOCK_HEIGHT * BLOCK_SIZE`, `M = MATRIX_BLOCK_WIDTH * BLOCK_SIZE`, or potentially less (a smaller matrix can be easily extended with zeroes to reach the proper dimensions, and we do so implicitly in our computations). 
This should be changed in the future, i.e. we will probably want to hold block_weight and block_height values for each matrix separately.

Suggestion for the future: initialize the testing structure once (`scylla_test --init?), only clear them up every time the tests are run, in order to improve testing performance. (Unless we want to test structure initialization, which we ought to do, but we could delegate such 'slow' tests to a separate set).

2021-03-16 22:16 UTC, jbhayven commented on include/scylla_blas/routines.hh
> +    void zdscal(const double alpha, vector <zdouble> &X);
Perhaps in operations like these we could additionally return the non-const vector as a result.

2021-03-16 22:16 UTC, jbhayven commented on include/scylla_blas/routines.hh
> +                        const double alpha, const vector<double> &X, const vector<double> &Y);
Perhaps we want to allow for passing a matrix handle as a parameter for higher flexibility in this and many other operations, as it is in the original header – the user might want to point to a matrix they want to modify, rather than have a new one created (e.g. due to performance reasons – creating a brand new matrix is costly, much more so than clearing one and refilling it).

2021-03-29 15:23 UTC, Rhantolq requested changes

2021-03-29 15:23 UTC, Rhantolq commented on include/scylla_blas/structure/matrix_block.hh
> +using LOVE = std::map<scylla_blas::index_type, scylla_blas::vector_segment<T>>;
The name LOVE always confuses me 🤔

2021-03-29 15:23 UTC, Rhantolq commented on include/scylla_blas/structure/matrix_block.hh
> +using LOVE = std::map<scylla_blas::index_type, scylla_blas::vector_segment<T>>;
Add a comment at least?

2021-03-29 15:23 UTC, Rhantolq commented on src/scylla_blas/queue/scylla_queue.cc
> +    if(out_size != sizeof(task)) {
if (

2021-03-29 15:23 UTC, Rhantolq commented on src/main.cc
>      if(op.is_init) {
if (

2021-03-29 17:00 UTC, jbhayven commented on include/scylla_blas/queue/scylla_queue.hh
> +} multiplication_order;
Makes sense.

2021-03-29 17:00 UTC, jbhayven commented on include/scylla_blas/structure/matrix_block.hh
> +using LOVE = std::map<scylla_blas::index_type, scylla_blas::vector_segment<T>>;
Tbh this whole thing needs a thorough reformat. I'll try to think of something.

2021-04-02 17:23 UTC, Lorak-mmk requested changes
Overall good. I'd really like to see some comments - a few words explaining what each class represents and what each method does, it's quite hard for me to understand it all right now.

2021-04-02 17:23 UTC, Lorak-mmk commented on include/scylla_blas/matrix.hh
> +     */
I don't understand this comment, can you elaborate more?

2021-04-03 19:40 UTC, Rhantolq requested changes
partial review

2021-04-03 23:36 UTC, jbhayven commented on src/main.cc
> +    if (std::count_if (args.begin(), args.end(), [&](const std::string& s){ return vm.count(s); }) != 1)
That's what you get for using "replace_all" :) I'll fix this, sure.

2021-04-03 23:37 UTC, jbhayven commented on src/scylla_blas/matrix.cc
> +    scmd::query_result result = session->execute(fmt::format("SELECT * FROM blas.matrix_meta WHERE id = {0};", id));
Fair point. I'll try it.

2021-04-03 23:39 UTC, jbhayven commented on src/scylla_blas/matrix.cc
> +    result.next_row(); // there must be exactly one!
I guess an exception will be thrown automatically? Adding a custom comment won't hurt though.

2021-04-04 00:12 UTC, jbhayven commented on src/scylla_blas/blas_level_3.cc
> +    matrix<T> C = matrix<T>::init_and_return(this->_session, C_id, A.rows, B.columns);
That's a fair point, but implementing it this way would result in a new layer of boilerplate (even if only to create a matrix and call the other overload). If you have an idea of how to implement this neatly – let me know. 

I don't think the potential overhead is a big issue (but an issue nevertheless). However, I do see how implementing this in the way you've described could make benchmarking easier and more reliable (e.g. a user could initialize all matrices in advance and measure only the time spent on actual computations).

Suggestion: let's leave it for now as it is (otherwise we'd need to rework the entire header for consistency, which happens to be a little tedious), and change it while working on the rest of the implementations.

2021-04-04 00:14 UTC, jbhayven commented on src/scylla_blas/blas_level_3.cc
> +    scylla_queue::create_queue(this->_session, multiplication_queue_id, false, true);
The idea was to allow for independent computations ordered by various processes / threads. A member of routine_factory? Aye, fair enough, I guess this could do the trick.

2021-04-04 00:31 UTC, jbhayven commented on src/scylla_blas/blas_level_3.cc
> +            multiplication_queue.produce({
Keeping worker count in the routine factory – great!

Grouping... meh. I mean, it sounds reasonable, but in the end you will get a number of calls larger by an order of magnitude during the actual computation, so... why bother thinning up the queue when it's not the main blocker? 

By the way, optimally the block size ought to be so large that there would be rather few subtasks anyway. 

On the other hand, with a large distribution in mind (where many subtasks is still good!), could we have a batch_produce queue method, accepting a whole collection of tasks at once? If we could, we could readily use it in our planning routines (like the one above).

2021-04-04 00:49 UTC, jbhayven commented on include/scylla_blas/matrix.hh
> +     */
I wanted to have a handy init_matrix() returning the initialized matrix. However, there might be instances where such behavior would be undesired, only wasting user's time constructing objects that would never be used (for instance, if the user wanted to initialize a matrix in advance, but not use it until some point much later in the program's life, just like I described in an earlier comment).

2021-04-04 00:50 UTC, jbhayven commented on src/scylla_blas/blas_level_3.cc
> +    matrix<T> C = matrix<T>::init_and_return(this->_session, C_id, A.rows, B.columns);
Actually, I think I'm growing more and more favorable of this change. This would make our scheduler somewhat cleaner and clearer. Let's leave it for the next time, though.

2021-04-04 17:28 UTC, Lorak-mmk commented on src/scylla_blas/blas_level_3.cc
> +    matrix<T> C = matrix<T>::init_and_return(this->_session, C_id, A.rows, B.columns);
I get why making 2 overloads would be problematic - but if that is not an option, then I think the better solution is to have a destination argument rather than creating new vector/matrix each time. Sure, we can leave it for later, but in my opinion it will have to be addressed.

2021-04-04 17:31 UTC, Lorak-mmk commented on src/scylla_blas/blas_level_3.cc
> +            multiplication_queue.produce({
"By the way, optimally the block size ought to be so large that there would be rather few subtasks anyway." - if that's the case, then what I said is probably non-issue.
"On the other hand, with a large distribution in mind (where many subtasks is still good!), could we have a batch_produce queue method, accepting a whole collection of tasks at once?" - That's actually a great idea, idk why I didn't think of that while writing queue. Shouldn't be too hard to implement, I can try to do it soon.

2021-04-04 17:33 UTC, Lorak-mmk commented on src/scylla_blas/matrix.cc
> +    result.next_row(); // there must be exactly one!
"as the default error message might potentially be hard to understand." - that's exactly why I'd like to see explicit throw here.

2021-04-04 17:34 UTC, Lorak-mmk commented on src/scylla_blas/matrix.cc
> +    scmd::query_result result = session->execute(fmt::format("SELECT * FROM blas.matrix_meta WHERE id = {0};", id));
You can have static unique_ptr, and check is it is null before using the statement - if it is, prepare it, and then use, else just use.

2021-04-05 12:41 UTC, Lorak-mmk approved these changes

2021-04-05 12:41 UTC, Lorak-mmk commented on src/scylla_blas/matrix.cc
> +{ }
No newline at the end :<

2021-04-05 19:41 UTC, Rhantolq approved these changes

2021-04-05 20:06 UTC, merged